
application: emailmereminder
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /.*
  script: emailmereminder.py

libraries:
- name: jinja2
  version: latest
- name: markupsafe
  version: latest
